<a href="https://colab.research.google.com/github/jimmiychen/practice/blob/main/101_NumPy_Exercises_for_Data_Analysis_(Python).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **101 NumPy Exercises for Data Analysis (Python)**

## **1. Import numpy as np and see the version**
Difficulty Level: L1

Q. Import numpy as np and print the version number.

In [1]:
import numpy as np

print(np.__version__)

1.19.5


## **2. How to create a 1D array?**
Difficulty Level: L1

Q. Create a 1D array of numbers from 0 to 9

In [3]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


## **3. How to create a boolean array?**
Difficulty Level: L1

Q. Create a 3×3 numpy array of all True’s

In [5]:
a=np.ones((3,3),dtype=bool)
print(a,"\n")
b=np.full((3,3),True,dtype=bool)
print(b)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# **4. How to extract items that satisfy a given condition from 1D array?**
Difficulty Level: L1

Q. Extract all odd numbers from arr

In [7]:
a=np.arange(10)
print(a,"\n")
a=a[a%2==1]
print(a)

[0 1 2 3 4 5 6 7 8 9] 

[1 3 5 7 9]


# **5. How to replace items that satisfy a condition with another value in numpy array?**
Difficulty Level: L1

Q. Replace all odd numbers in arr with -1

In [8]:
a=np.arange(10)
print(a,"\n")
a[a[a%2==1]]=-1
print(a)

[0 1 2 3 4 5 6 7 8 9] 

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# **6. How to replace items that satisfy a condition without affecting the original array?**
Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr