<a href="https://colab.research.google.com/github/jimmiychen/practice/blob/main/101_NumPy_Exercises_for_Data_Analysis_(Python).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **101 NumPy Exercises for Data Analysis (Python)**

## **1. Import numpy as np and see the version**
Difficulty Level: L1

Q. Import numpy as np and print the version number.

In [3]:
import numpy as np

print(np.__version__)

1.19.5


## **2. How to create a 1D array?**
Difficulty Level: L1<br>

Q. Create a 1D array of numbers from 0 to 9 <br><br>
Desired output:


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


## **3. How to create a boolean array?**
Difficulty Level: L1

Q. Create a 3×3 numpy array of all True’s

In [ ]:
a=np.ones((3,3),dtype=bool)
print("method1:",a)
print("\n")
b=np.full((3,3),True,dtype=bool)
print("method2:",b)

method1: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 

method2: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# **4. How to extract items that satisfy a given condition from 1D array?**
Difficulty Level: L1

Q. Extract all odd numbers from arr<br><br>


Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])<br><br>
Desired output:<br>
array([1, 3, 5, 7, 9])

In [ ]:
a=np.arange(10)
print(a)
print("\n")
a=a[a%2==1]
print(a)

[0 1 2 3 4 5 6 7 8 9] 

[1 3 5 7 9]


# **5. How to replace items that satisfy a condition with another value in numpy array?**
Difficulty Level: L1<br>

Q. Replace all odd numbers in arr with -1 <br><br>
Input:


arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])<br><br>
Desired Output:<br>
array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
a=np.arange(10)
print(a)
print("\n")
a[a[a%2==1]]=-1
print(a)

[0 1 2 3 4 5 6 7 8 9] 

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# **6. How to replace items that satisfy a condition without affecting the original array?**
Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr
<br><br>Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])<br><br>
Desired Output:

out
array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])<br>
arr
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print("錯誤:")
a=np.arange(10)
out=a
out[out[out%2==1]]=-1
print("a=",a)
print("out=",out)
print("\n")
print("正確:")
b=np.arange(10)
out=np.where(b%2==1,-1,b)
print("b=",b)
print("out=",out)
print("\n")

錯誤:
a= [ 0 -1  2 -1  4 -1  6 -1  8 -1]
out= [ 0 -1  2 -1  4 -1  6 -1  8 -1]


正確:
b= [0 1 2 3 4 5 6 7 8 9]
out= [ 0 -1  2 -1  4 -1  6 -1  8 -1]




# **7. How to reshape an array?**
Difficulty Level: L1

Q. Convert a 1D array to a 2D array with 2 rows<br><br>
Input:

np.arange(10)

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])<br><br>
Desired Output:<br>

array([[0, 1, 2, 3, 4],<br>
[5, 6, 7, 8, 9]])

In [ ]:
a=np.arange(10)
print(a)
print("\n")
a=a.reshape(2,5)
print(a)

[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]]


# **8. How to stack two arrays vertically?**
Difficulty Level: L2<br>
Q. Stack arrays a and b vertically<br><br>
Input

a = np.arange(10).reshape(2,-1)<br>
b = np.repeat(1, 10).reshape(2,-1)<br><br>
Desired Output:<br>


array([[0, 1, 2, 3, 4],<br>
  [5, 6, 7, 8, 9],<br>
  [1, 1, 1, 1, 1],<br>
  [1, 1, 1, 1, 1]])

In [ ]:
a=np.arange(10).reshape(2,5)
b=np.full((2,5),1)
print(a,"\n")
print(b,"\n")
print(np.vstack([a,b]))

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[1 1 1 1 1]
 [1 1 1 1 1]] 

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# **9. How to stack two arrays horizontally?**
Difficulty Level: L2

Q. Stack the arrays a and b horizontally.<br><br>
Input<br>

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)<br><br>
Desired Output:<br>

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],<br>
[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
a=np.arange(10).reshape(2,5)
b=np.full((2,5),1)
print(a,"\n")
print(b,"\n")
print(np.hstack([a,b]))

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[1 1 1 1 1]
 [1 1 1 1 1]] 

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


# **10. How to generate custom sequences in numpy without hardcoding?**
Difficulty Level: L2

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.<br><br>

Input:


a = np.array([1,2,3])<br><br>
Desired Output:<br>

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
#np.repeat：复制的是多维数组的每一个元素
#np.tile：复制的是多维数组本身
a=np.arange(3)
print(a)
b=np.r_[np.repeat(a,3),np.tile(a,3)] #复制3次
#np.r_是按列连接两个矩阵，就是把两矩阵上下相加，要求列数相等，类似于pandas中的concat()。
#np.c_是按行连接两个矩阵，就是把两矩阵左右相加，要求行数相等，类似于pandas中的merge()。
print(b)

[1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


# **11. How to get the common items between two python numpy arrays?**
Difficulty Level: L2

Q. Get the common items between a and b
 <br>  <br> 
Input:

a = np.array([1,2,3,2,3,4,3,4,5,6]) <br> 
b = np.array([7,2,10,2,7,4,9,4,9,8]) <br><br>

Desired Output:

array([2, 4])

In [ ]:
a=np.array([1,2,3,2,3,4,3,4,5,6]) #直接創list
b=np.array([7,2,10,2,7,4,9,4,9,8]) #直接創list
c=np.intersect1d(a,b) #交集
print(c)

[2 4]


# **12. How to remove from one array those items that exist in another?**
Difficulty Level: L2

Q. From array a remove all items present in array b<br><br>

Input:

a = np.array([1,2,3,4,5])<br>
b = np.array([5,6,7,8,9])<br><br>
Desired Output:

array([1,2,3,4])

In [ ]:
a=np.array([1,2,3,4,5]) #直接創list
b=np.array([5,6,7,8,9]) #直接創list
c=np.setdiff1d(a,b) #差集
print(c)

[1 2 3 4]


# **13. How to get the positions where elements of two arrays match?**
Difficulty Level: L2


Q. Get the positions where elements of a and b match<br><br>

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])<br>
b = np.array([7,2,10,2,7,4,9,4,9,8])<br><br>
Desired Output:

(array([1, 3, 5, 7]),)

In [7]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
index=np.where(a==b) #回傳index
print(index)

(array([1, 3, 5, 7]),)


# **14. How to extract all numbers between a given range from a numpy array?**
Difficulty Level: L2

Q. Get all items between 5 and 10 from a.<br><br>

Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])<br><br>
Desired Output:

(array([6, 9, 10]),)

In [8]:
a=np.array([2,6,1,9,10,3,27])
index=np.where((a>=5)&(a<=10))
print(a[index])

[ 6  9 10]


# **15. How to make a python function that handles scalars to work on numpy arrays?**
Difficulty Level: L2

Q. Convert the function maxx that works on two scalars, to work on two arrays.<br><br>

Input:


def maxx(x, y):<br>
    """Get the maximum of two items"""<br>
     &emsp;&emsp;&emsp;if x >= y:<br>
        &emsp;&emsp;&emsp;&emsp;&emsp;return <br>
    &emsp;&emsp;&emsp;else:<br>
        &emsp;&emsp;&emsp;&emsp;&emsp;return y<br>

maxx(1, 5)<br>
 5<br><br>
Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])<br>
b = np.array([6, 3, 4, 8, 9, 7, 1])<br>
pair_max(a, b)<br>
array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

# **16. How to swap two columns in a 2d numpy array?**
Difficulty Level: L2

Q. Swap columns 1 and 2 in the array arr.<br><br>

arr = np.arange(9).reshape(3,3)<br>
arr

In [21]:
a=np.arange(9).reshape(3,3)
print(a)
a[:,[2,1,0]]=a[:,[0,1,2]]  # 0,1,2 col 轉成 2,1,0 col
print("\n")
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[2 1 0]
 [5 4 3]
 [8 7 6]]


# 17. How to swap two rows in a 2d numpy array?
Difficulty Level: L2

Q. Swap rows 1 and 2 in the array arr:<br><br>

arr = np.arange(9).reshape(3,3)<br>
arr

In [22]:
a=np.arange(9).reshape(3,3)
print(a)
a[[2,1,0],:]=a[[0,1,2],:]  # 0,1,2 row 轉成 2,1,0 row
print("\n")
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[6 7 8]
 [3 4 5]
 [0 1 2]]


# **18. How to reverse the rows of a 2D array?**
Difficulty Level: L2

Q. Reverse the rows of a 2D array arr.

In [29]:
a=np.arange(9).reshape(3,3)
print(a)

print("\n")
b=np.flip(a,axis=0) # arr[start:end:stepsize] or np.flip(arr,axis=None)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[6 7 8]
 [3 4 5]
 [0 1 2]]


# **19. How to reverse the columns of a 2D array?**
Difficulty Level: L2

Q. Reverse the columns of a 2D array arr.

In [30]:
a=np.arange(9).reshape(3,3)
print(a)

print("\n")
b=np.flip(a,axis=1) # arr[start:end:stepsize] or np.flip(arr,axis=None)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[2 1 0]
 [5 4 3]
 [8 7 6]]


# **20. How to create a 2D array containing random floats between 5 and 10?**
Difficulty Level: L2


Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [28]:
a=np.random.rand(15).reshape(5,3)
a=5+(a*(10-5)) #線性內插法
print(a)

print("\n")
b=np.random.randint(low=5,high=10,size=(5,3))+np.random.random((5,3))
print(b)

[[7.86788142 9.6717887  8.18324668]
 [7.50665503 6.78794406 8.09402581]
 [8.32531744 5.91626399 9.68712925]
 [6.35921462 7.13671232 9.81452011]
 [6.13312408 7.88638474 5.37236507]]


[[7.21091675 8.09883054 8.85832404]
 [6.72708105 8.17652195 6.04041001]
 [7.23676067 9.20989881 8.66176394]
 [5.37331636 8.2220575  8.79551312]
 [7.94310443 5.86218297 7.9272815 ]]


# **21. How to print only 3 decimal places in python numpy array?**
Difficulty Level: L1

Q. Print or show only 3 decimal places of the numpy array rand_arr.<br><br>

Input:

rand_arr = np.random.random((5,3))

In [65]:
a=np.random.rand(15).reshape(5,3)
np.set_printoptions(suppress=False) 
print(a)
print("\n")
np.set_printoptions(precision=3,suppress=True) #太小的supress掉,有.00或科學記號就忽略不計
print(a)
print("\n")
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)}) #強制補到3位
print(a)

[[0.262 0.456 0.683]
 [0.696 0.284 0.38 ]
 [0.181 0.789 0.057]
 [0.697 0.779 0.777]
 [0.259 0.374 0.588]]


[[0.262 0.456 0.683]
 [0.696 0.284 0.38 ]
 [0.181 0.789 0.057]
 [0.697 0.779 0.777]
 [0.259 0.374 0.588]]


[[0.262 0.456 0.683]
 [0.696 0.284 0.380]
 [0.181 0.789 0.057]
 [0.697 0.779 0.777]
 [0.259 0.374 0.588]]


# **22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?**
Difficulty Level: L1

Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)<br><br>

Input:

Create the random array<br>
np.random.seed(100)<br>
rand_arr = np.random.random([3,3])/1e3<br>
rand_arr

array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],<br>
        [  8.447761e-04,   4.718856e-06,   1.215691e-04],<br>
        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])<br><br>
Desired Output:

array([[ 0.000543,  0.000278,  0.000425],<br>
        [ 0.000845,  0.000005,  0.000122],<br>
        [ 0.000671,  0.000826,  0.000137]])<br>

In [56]:
a=np.random.rand(9).reshape(3,3)/1e3
np.set_printoptions(suppress=False) 
print(a)
print("\n")
np.set_printoptions(precision=6,suppress=True) #太小的supress掉,有.00或科學記號就忽略不計
print(a)
print("\n")
np.set_printoptions(formatter={'float': lambda x: "{0:0.6f}".format(x)}) #強制補到6位
print(a)

[[4.905e-04 2.274e-04 2.544e-04]
 [5.803e-05 4.344e-04 3.118e-04]
 [6.963e-04 3.778e-04 1.796e-04]]


[[0.00049  0.000227 0.000254]
 [0.000058 0.000434 0.000312]
 [0.000696 0.000378 0.00018 ]]


[[0.000490 0.000227 0.000254]
 [0.000058 0.000434 0.000312]
 [0.000696 0.000378 0.000180]]


# **23. How to limit the number of items printed in output of numpy array?**
Difficulty Level: L1

Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.<br><br>


Input:

a = np.arange(15)<br>
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])<br><br>
Desired Output:

array([ 0,  1,  2, ..., 12, 13, 14])

In [68]:
a=np.arange(15)
print(a)
print("\n")
np.set_printoptions(threshold=5) #會用...代替
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


[ 0  1  2 ... 12 13 14]
